// frontend/src/shared/components/ConfirmationScreen.tsx
import { useNavigate } from "react-router";

interface ConfirmationScreenProps {
  title?: string;
  message?: string;
  subMessage?: string;
  returnLabel?: string;
  returnRoute?: string;
  showReturnButton?: boolean;
  iconName?: string;
  iconColor?: string;
  iconBg?: string;
  children?: React.ReactNode;
}

export function ConfirmationScreen({
  title = "Completed Successfully!",
  message = "Your request has been processed.",
  subMessage = "",
  returnLabel = "Return to Pending Reviews",
  returnRoute = "/team-inbox",
  showReturnButton = true,
  iconName = "check_circle",
  iconColor = "#10B981",
  iconBg = "linear-gradient(135deg, #E3FCEF 0%, #D1FAE5 100%)",
  children
}: ConfirmationScreenProps) {
  const navigate = useNavigate();

  return (
    <div className="flex flex-col items-center justify-center text-center max-w-[620px] mx-auto my-[40px] px-[40px] py-[56px] bg-white border border-slate-200/80 rounded-[20px] shadow-[0_20px_50px_rgba(16,24,40,0.12)] font-sans animate-fade-in relative z-10 w-full">
      <div 
        className="w-[88px] h-[88px] rounded-full flex items-center justify-center mb-[28px] shadow-[0_8px_24px_rgba(16,185,129,0.2)]"
        style={{ background: iconBg }}
      >
        <span className="material-icons text-[52px]" style={{ color: iconColor }}>
          {iconName}
        </span>
      </div>
      
      <h2 className="m-0 mb-3 text-[26px] font-extrabold text-[#172B4D] tracking-[-0.3px]" style={{ fontFamily: "'Outfit', sans-serif" }}>
        {title}
      </h2>
      
      <p className="m-0 text-[#505F79] text-[15px] leading-relaxed max-w-[440px]">
        {message}
      </p>
      
      {subMessage && (
        <p className="mt-2.5 mb-0 text-[#6B778C] text-[13px] leading-relaxed max-w-[440px]">
          {subMessage}
        </p>
      )}
      
      <div className="mt-8 flex gap-4 justify-center flex-wrap w-full">
        {showReturnButton && (
          <button 
            type="button" 
            onClick={() => navigate(returnRoute)}
            className="px-7 py-3 rounded-xl font-bold text-[14px] text-white border-none cursor-pointer shadow-[0_4px_14px_rgba(16,185,129,0.3)] transition-all duration-200 hover:-translate-y-px hover:shadow-[0_8px_20px_rgba(16,185,129,0.4)]"
            style={{ background: "linear-gradient(135deg, #10B981, #059669)" }}
          >
            {returnLabel}
          </button>
        )}
        {children}
      </div>
    </div>
  );
}

// frontend/src/app/shared/components/confirmation-screen/confirmation-screen.component.ts
import { Component, Input, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-confirmation-screen',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="success-screen animate-fade-in">
      <div class="success-icon-wrapper" [style.background]="iconBg">
        <span class="material-icons success-icon" [style.color]="iconColor">{{ iconName }}</span>
      </div>
      <h2 class="success-title">{{ title }}</h2>
      <p class="success-message">{{ message }}</p>
      @if (subMessage) {
        <p class="success-submessage">{{ subMessage }}</p>
      }
      <div class="success-actions">
        @if (showReturnButton) {
          <button type="button" class="btn-return" (click)="onReturn()">{{ returnLabel }}</button>
        }
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styles: [`
    .success-screen {
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      text-align: center; max-width: 620px; margin: 40px auto; padding: 56px 40px;
      background: #FFFFFF; border: 1px solid rgba(226,232,240,0.8); border-radius: 20px;
      box-shadow: 0 20px 50px rgba(16,24,40,0.12); font-family: 'Inter', sans-serif;
    }
    .success-icon-wrapper {
      width: 88px; height: 88px; border-radius: 50%;
      background: linear-gradient(135deg, #E3FCEF 0%, #D1FAE5 100%);
      display: flex; align-items: center; justify-content: center;
      margin-bottom: 28px; box-shadow: 0 8px 24px rgba(16,185,129,0.2);
    }
    .success-icon { font-size: 52px; color: #10B981; }
    .success-title {
      margin: 0 0 12px; font-size: 26px; font-weight: 800; color: #172B4D;
      font-family: 'Outfit', sans-serif; letter-spacing: -0.3px;
    }
    .success-message { margin: 0; color: #505F79; font-size: 15px; line-height: 1.6; max-width: 440px; }
    .success-submessage { margin: 10px 0 0; color: #6B778C; font-size: 13px; line-height: 1.6; max-width: 440px; }
    .success-actions { margin-top: 32px; display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; }
    .btn-return {
      padding: 12px 28px; border-radius: 10px; font-weight: 700; font-size: 14px;
      background: linear-gradient(135deg, #10B981, #059669); color: white; border: none;
      cursor: pointer; box-shadow: 0 4px 14px rgba(16,185,129,0.3); transition: all 0.2s;
    }
    .btn-return:hover { transform: translateY(-1px); box-shadow: 0 8px 20px rgba(16,185,129,0.4); }
  `]
})
export class ConfirmationScreenComponent {
  private router = inject(Router);

  @Input() title = 'Completed Successfully!';
  @Input() message = 'Your request has been processed.';
  @Input() subMessage = '';
  @Input() returnLabel = 'Return to Pending Reviews';
  @Input() returnRoute = '/team-inbox';
  @Input() showReturnButton = true;
  @Input() iconName = 'check_circle';
  @Input() iconColor = '#10B981';
  @Input() iconBg = 'linear-gradient(135deg, #E3FCEF 0%, #D1FAE5 100%)';

  onReturn() {
    this.router.navigate([this.returnRoute]);
  }
}
